name: brew pr-pull

on:
  pull_request_target:
    types:
      - labeled

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - id: setup-git
        uses: Homebrew/actions/git-user-config@master

      - id: pr-pull
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull \
            --no-upload \
            --debug \
            --tap="$GITHUB_REPOSITORY" \
            --root-url https://ghcr.io/v2/mmalenic/homebrew-evlist \
            "$PULL_REQUEST"

      - id: pr-upload
        working-directory: ${{ steps.pr-pull.outputs.bottle_path }}
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: mmalenic
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
        run: |
          brew pr-upload \
            --debug \
            --root-url= https://ghcr.io/v2/mmalenic/homebrew-evlist

      - id: push
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - id: delete-branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin "$BRANCH"
